apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avgexchange-ingress
  namespace: avgexchange
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: avgexchange.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avgexchange-frontend
                port:
                  number: 80

    - host: www.avgexchange.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avgexchange-frontend
                port:
                  number: 80

    - host: api.avgexchange.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avgexchange-backend
                port:
                  number: 4010
